package qbittorrent

type Torrent struct {
	Hash              string  `json:"hash"`
	AddedOn           int     `json:"added_on"`
	AmountLeft        int     `json:"amount_left"`
	AutoTmm           bool    `json:"auto_tmm"`
	Category          string  `json:"category"`
	Completed         int     `json:"completed"`
	CompletedOn       int     `json:"completed_on"`
	DLLimit           int64   `json:"dl_limit"`
	DLSpeed           int64   `json:"dlspeed"`
	Downloaded        int     `json:"downloaded"`
	DownloadedSession int     `json:"downloaded_session"`
	ETA               int     `json:"eta"`
	Name              string  `json:"name"`
	Progress          float32 `json:"progress"`
	ULSpeed           int64   `json:"ulspeed"`
	Ratio             float32 `json:"ratio"`
	State             string  `json:"state"`
}

type Preferences struct {
	AddTrackers                      string `json:"add_trackers"`
	AddTrackersEnabled               bool   `json:"add_trackers_enabled"`
	AltDlLimit                       int    `json:"alt_dl_limit"`
	AltUpLimit                       int    `json:"alt_up_limit"`
	AlternativeWebuiEnabled          bool   `json:"alternative_webui_enabled"`
	AlternativeWebuiPath             string `json:"alternative_webui_path"`
	AnonymousMode                    bool   `json:"anonymous_mode"`
	AutoDeleteMode                   int    `json:"auto_delete_mode"`
	AutoTmmEnabled                   bool   `json:"auto_tmm_enabled"`
	AutorunEnabled                   bool   `json:"autorun_enabled"`
	AutorunProgram                   string `json:"autorun_program"`
	BannedIPs                        string `json:"banned_IPs"`
	BittorrentProtocol               int    `json:"bittorrent_protocol"`
	BypassAuthSubnetWhitelist        string `json:"bypass_auth_subnet_whitelist"`
	BypassAuthSubnetWhitelistEnabled bool   `json:"bypass_auth_subnet_whitelist_enabled"`
	BypassLocalAuth                  bool   `json:"bypass_local_auth"`
	CategoryChangedTmmEnabled        bool   `json:"category_changed_tmm_enabled"`
	CreateSubfolderEnabled           bool   `json:"create_subfolder_enabled"`
	Dht                              bool   `json:"dht"`
	DlLimit                          int    `json:"dl_limit"`
	DontCountSlowTorrents            bool   `json:"dont_count_slow_torrents"`
	DyndnsDomain                     string `json:"dyndns_domain"`
	DyndnsEnabled                    bool   `json:"dyndns_enabled"`
	DyndnsPassword                   string `json:"dyndns_password"`
	DyndnsService                    int    `json:"dyndns_service"`
	DyndnsUsername                   string `json:"dyndns_username"`
	Encryption                       int    `json:"encryption"`
	ExportDir                        string `json:"export_dir"`
	ExportDirFin                     string `json:"export_dir_fin"`
	ForceProxy                       bool   `json:"force_proxy"`
	IncompleteFilesExt               bool   `json:"incomplete_files_ext"`
	IpFilterEnabled                  bool   `json:"ip_filter_enabled"`
	IpFilterPath                     string `json:"ip_filter_path"`
	IpFilterTrackers                 bool   `json:"ip_filter_trackers"`
	LimitLanPeers                    bool   `json:"limit_lan_peers"`
	LimitTcpOverhead                 bool   `json:"limit_tcp_overhead"`
	LimitUtpRate                     bool   `json:"limit_utp_rate"`
	ListenPort                       int    `json:"listen_port"`
	Locale                           string `json:"locale"`
	Lsd                              bool   `json:"lsd"`
	MailNotificationAuthEnabled      bool   `json:"mail_notification_auth_enabled"`
	MailNotificationEmail            string `json:"mail_notification_email"`
	MailNotificationEnabled          bool   `json:"mail_notification_enabled"`
	MailNotificationPassword         string `json:"mail_notification_password"`
	MailNotificationSender           string `json:"mail_notification_sender"`
	MailNotificationSmtp             string `json:"mail_notification_smtp"`
	MailNotificationSslEnabled       bool   `json:"mail_notification_ssl_enabled"`
	MailNotificationUsername         string `json:"mail_notification_username"`
	MaxActiveDownloads               int    `json:"max_active_downloads"`
	MaxActiveTorrents                int    `json:"max_active_torrents"`
	MaxActiveUploads                 int    `json:"max_active_uploads"`
	MaxConnec                        int    `json:"max_connec"`
	MaxConnecPerTorrent              int    `json:"max_connec_per_torrent"`
	MaxRatio                         int    `json:"max_ratio"`
	MaxRatioAct                      int    `json:"max_ratio_act"`
	MaxRatioEnabled                  bool   `json:"max_ratio_enabled"`
	MaxSeedingTime                   int    `json:"max_seeding_time"`
	MaxSeedingTimeEnabled            bool   `json:"max_seeding_time_enabled"`
	MaxUploads                       int    `json:"max_uploads"`
	MaxUploadsPerTorrent             int    `json:"max_uploads_per_torrent"`
	Pex                              bool   `json:"pex"`
	PreallocateAll                   bool   `json:"preallocate_all"`
	ProxyAuthEnabled                 bool   `json:"proxy_auth_enabled"`
	ProxyIp                          string `json:"proxy_ip"`
	ProxyPassword                    string `json:"proxy_password"`
	ProxyPeerConnections             bool   `json:"proxy_peer_connections"`
	ProxyPort                        int    `json:"proxy_port"`
	ProxyTorrentsOnly                bool   `json:"proxy_torrents_only"`
	ProxyType                        int    `json:"proxy_type"`
	ProxyUsername                    string `json:"proxy_username"`
	QueueingEnabled                  bool   `json:"queueing_enabled"`
	RandomPort                       bool   `json:"random_port"`
	RssAutoDownloadingEnabled        bool   `json:"rss_auto_downloading_enabled"`
	RssMaxArticlesPerFeed            int    `json:"rss_max_articles_per_feed"`
	RssProcessingEnabled             bool   `json:"rss_processing_enabled"`
	RssRefreshInterval               int    `json:"rss_refresh_interval"`
	SavePath                         string `json:"save_path"`
	SavePathChangedTmmEnabled        bool   `json:"save_path_changed_tmm_enabled"`
	// ScanDirs                           string `json:"scan_dirs"`
	ScheduleFromHour                   int    `json:"schedule_from_hour"`
	ScheduleFromMin                    int    `json:"schedule_from_min"`
	ScheduleToHour                     int    `json:"schedule_to_hour"`
	ScheduleToMin                      int    `json:"schedule_to_min"`
	SchedulerDays                      int    `json:"scheduler_days"`
	SchedulerEnabled                   bool   `json:"scheduler_enabled"`
	SlowTorrentDlRateThreshold         int    `json:"slow_torrent_dl_rate_threshold"`
	SlowTorrentInactiveTimer           int    `json:"slow_torrent_inactive_timer"`
	SlowTorrentUlRateThreshold         int    `json:"slow_torrent_ul_rate_threshold"`
	SslCert                            string `json:"ssl_cert"`
	SslKey                             string `json:"ssl_key"`
	StartPausedEnabled                 bool   `json:"start_paused_enabled"`
	TempPath                           string `json:"temp_path"`
	TempPathEnabled                    bool   `json:"temp_path_enabled"`
	TorrentChangedTmmEnabled           bool   `json:"torrent_changed_tmm_enabled"`
	UpLimit                            int    `json:"up_limit"`
	Upnp                               bool   `json:"upnp"`
	UseHttps                           bool   `json:"use_https"`
	WebUiAddress                       string `json:"web_ui_address"`
	WebUiClickjackingProtectionEnabled bool   `json:"web_ui_clickjacking_protection_enabled"`
	WebUiCsrfProtectionEnabled         bool   `json:"web_ui_csrf_protection_enabled"`
	WebUiDomainList                    string `json:"web_ui_domain_list"`
	WebUiHostHeaderValidationEnabled   bool   `json:"web_ui_host_header_validation_enabled"`
	WebUiPassword                      string `json:"web_ui_password"`
	WebUiPort                          int    `json:"web_ui_port"`
	WebUiUpnp                          bool   `json:"web_ui_upnp"`
	WebUiUsername                      string `json:"web_ui_username"`
}
